# list the AC peers for the server under [[ACs]] table

# PubKeyBase64: public key for the AC in base64 format.
# ExpireTime (epoch timestamp in seconds): peer key validation will fail when it expires.
[[ACs]]
PubKeyBase64 = "U2PEu/hwRRJTxGb+IXBmRdxMAbzk8ZLMvgfM8c5b6IFAGF/jWnAKKY+a5OFYLR+Fv9iVBdnENtCYsqEJiFxwgg=="
ExpireTime = 1924991999
