networks:
  server:
  ac:
  agent:

services:
  # nhp-base:
  #   image: opennhp-base
  #   build: 
  #     context: ..
  #     dockerfile: ./docker/Dockerfile.base
  #   container_name: nhp-base
  #   restart: always

  nhp-server:
    image: opennhp-server
    build: 
      context: ../..
      dockerfile: ./opennhp/docker/Dockerfile.server
    container_name: nhp-server
    restart: always
    networks:
      - ac
    volumes:
      - ${PWD}/nhp-server/etc/:/nhp-server/etc/:rw
      - ${PWD}/nhp-server/plugins/example/etc/:/nhp-server/plugins/example/etc/:rw
      - ${PWD}/nhp-server/plugins/passcode/etc/:/nhp-server/plugins/passcode/etc/:rw
      - ${PWD}/nhp-server/logs/:/nhp-server/logs/:rw
    ports:
      - "62206:62206/udp"
      - "62206:62206/tcp"

  nhp-ac:
    image: opennhp-ac
    container_name: nhp-ac
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile.ac
    volumes:
      - ${PWD}/nhp-ac/etc/:/nhp-ac/etc/
      - ${PWD}/nhp-ac/logs/:/nhp-ac/logs/
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - nhp-server
    networks:
      - server
    ports:
      - "80:80"

  nhp-app:
    image: nginx:latest
    container_name: nhp-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - server

  nhp-agent:
    image: opennhp-agent
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile.agent
    container_name: nhp-agent
    restart: always
    volumes:
      - ${PWD}/nhp-agent/etc/:/nhp-agent/etc/:rw
#      - ${PWD}/nhp-agent/logs/:/nhp-agent/logs/:rw
    networks:
      - server