FROM opennhp-base:latest AS builder

FROM ubuntu:20.04  AS runtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y  wget \
    ca-certificates \
    nginx \
    iptables \
    tcpdump \
    ipset \
    git \
    curl \
    telnet \
    && rm -rf /var/lib/apt/lists/* 

COPY --from=builder /nhp-server/release/nhp-ac /nhp-ac 

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["nginx & /nhp-ac/nhp-acd run"]
#ENTRYPOINT ["/nhp-ac/nhp-acd", "run"]